version: '3'

services:
  vue:
    container_name: mdgkb-client
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - ${VUE_APP_PORT}:${VUE_APP_PORT}
    stdin_open: true
    tty: true
    network_mode: "host"